version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./createSetEnv.sh
    destination: /home/ubuntu
  - source: ./infrastructure/aws/cloudwatch/awslogs.conf
    destination: /home/ubuntu
  - source: ./awslogs.service
    destination: /etc/systemd/system
  - source: ./build/libs/csye6225app.war
    destination: /var/lib/tomcat8/webapps

hooks:
  AfterInstall:
   - location: ./awsLogServiceSetup.sh
   - location: ./createSetEnv.sh
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu
